version: "3.1"
services:

  mysql:
    image: mysql:8.0
    container_name: st-mysql
    working_dir: /application
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=persistence
    ports:
      - "3306:3306"

  webserver:
    image: nginx:alpine
    container_name: st-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  php-fpm:
    build: docker/php-fpm
    container_name: st-php
    working_dir: /application
    volumes:
      - .:/application


  app_messenger:
    container_name: st-messenger
    depends_on:
      - php-fpm
      - mysql
    restart: on-failure
    working_dir: /application
    build: ./docker/consumer/
    volumes:
      - .:/application
      - ./docker/consumer/supervisord.conf:/etc/supervisord.conf
